Repository Majorfi/bowswap_ui, pull requests merged in 2021-09, with the labels that each got.

#20 Feature/Slippage too high message
  components/Bowswap/index.js
  utils/actions.js
Labels: enhancement

#23 Feature/adding eurtVault
  components/Bowswap/index.js
  contexts/useAccount.js
  pages/_app.js
  scripts/LISTING.json
  scripts/findPath.js
  utils/BOWSWAP_CRV_EUR_VAULTS.json
Labels: enhancement

#29 Feature/Notification Counter
  components/Commons/Tabs.js
  components/YVempire/index.js
  contexts/useAccount.js
  pages/_app.js
Labels: Feature 🚀

#31 Fix/3M gas + V2 fallback
  components/Bowswap/index.js
  utils/actions.js
Labels: Bug 🐞

#33 Feature/yvCurve-MIM vault
  scripts/LISTING.json
  scripts/findPath.js
  utils/BOWSWAP_CRV_USD_VAULTS.json
  utils/currentPaths.js
Labels: Improvement 🦄

#36 Feature/3Pool
  scripts/LISTING.json
  scripts/findPath.js
  utils/BOWSWAP_CRV_V2_VAULTS.json
  utils/currentPaths.js
Labels: Improvement 🦄

#38 Feature/persist from to
  components/Bowswap/InputTokenDisabled.js
  components/Bowswap/ModalVaultList.js
  components/Bowswap/index.js
  pages/_app.js
Labels: Improvement 🦄

#37 Feature/from to order
  components/Bowswap/ModalVaultList.js
  components/Bowswap/index.js
Labels: Improvement 🦄

#39 BugFix/Crash on ToVault & autocomplet
  components/Bowswap/index.js
Labels: Bug 🐞

#40 Feature/DisplayEnvVariables
  next.config.js
Labels: Improvement 🦄

#41 Feature/swapWithSignature
  components/Bowswap/InputToken.js
  components/Bowswap/index.js
  next.config.js
  utils/actions.js
Labels: Feature 🚀, Improvement 🦄
